import guru.nidi.graphviz.attribute.Label;
import guru.nidi.graphviz.engine.Format;
import guru.nidi.graphviz.engine.Graphviz;
import guru.nidi.graphviz.model.MutableGraph;
import guru.nidi.graphviz.model.MutableNode;
import guru.nidi.graphviz.model.Node;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import static guru.nidi.graphviz.model.Factory.mutGraph;
import static guru.nidi.graphviz.model.Factory.mutNode;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
        MutableGraph g = mutGraph("test").setDirected(true);
        List<MutableNode> nodes = new ArrayList<>();
        nodes.add(mutNode("1").add((Label.of("A"))));
        nodes.add(mutNode("2").add((Label.of("B"))));
        nodes.add(mutNode("3").add((Label.of("A"))));
        nodes.get(0).addLink(nodes.get(1));
        nodes.get(1).addLink(nodes.get(2));
        for (MutableNode node: nodes) {
            g.add(node);
        }
        Graphviz.fromGraph(g).width(200).render(Format.PNG).toFile(new File("ex1m.png"));

    }

}
